baseURL: "https://ayasismail666.github.io/"
languageCode: "en-us"
title: "Ayas Ismail"
theme: "PaperMod"

params:
  author: "Ayas Ismail"
  description: "Cloud | Machine Learning | IoT"
  defaultTheme: light

  social:
    - name: "GitHub"
      url: "https://github.com/ayasismail666"
    - name: "LinkedIn"
      url: "https://linkedin.com/in/your-profile"
    - name: "Email"
      url: "mailto:yourname@email.com"

menu:
  main:
    - identifier: about
      name: "About"
      url: "/about/"
      weight: 10
    - identifier: projects
      name: "Projects"
      url: "/projects/"
      weight: 20
    - identifier: blog
      name: "Blog"
      url: "/blog/"
      weight: 30
